# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
development:
  stripe_api_key: sk_test_ktu2SLF9p140GZJq2iDef9OQ
  stripe_publishable_key: pk_test_cq0euKSMqWVsLgE0DUAdPGZ8
  TWILIO_ACCOUNT_SID: AC148c4775977fba877ccdbd9c07c94752
  TWILIO_AUTH_TOKEN: c6b713e3d47a9ff5201d9afce2e6d53b
  TWILIO_PHONE_NUMBER: 17207249689
test:
  stripe_api_key: sk_test_ktu2SLF9p140GZJq2iDef9OQ
  stripe_publishable_key: pk_test_cq0euKSMqWVsLgE0DUAdPGZ8
  TWILIO_ACCOUNT_SID: AC148c4775977fba877ccdbd9c07c94752
  TWILIO_AUTH_TOKEN: c6b713e3d47a9ff5201d9afce2e6d53b
  TWILIO_PHONE_NUMBER: 17207249689
